apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1alpha1","kind":"Task","metadata":{"annotations":{},"name":"apply-application-plan","namespace":"user1"},"spec":{"inputs":{"params":[{"description":"The name of the 3scale_toolbox remote","name":"destination"},{"description":"Name of the secret containing the 3scale_toolbox remotes list","name":"secretName"},{"description":"The system_name of the service","name":"serviceSystemName"},{"description":"The system_name of the plan to create","name":"systemName"},{"description":"The name of the plan to create","name":"name"}],"resources":[{"name":"api-artefacts","type":"git"}]},"steps":[{"args":["application-plan","apply","${inputs.params.destination}","${inputs.params.serviceSystemName}","${inputs.params.systemName}","--name=${inputs.params.name}"],"command":["3scale"],"env":[{"name":"HOME","value":"/config"}],"image":"nmasse/3scale-toolbox:master","name":"apply-application-plan","volumeMounts":[{"mountPath":"/config","name":"toolbox-config"}]}],"volumes":[{"name":"toolbox-config","secret":{"secretName":"${inputs.params.secretName}"}}]}}
  name: apply-application-plan
  namespace: user1
spec:
  params:
  - description: The name of the 3scale_toolbox remote
    name: destination
    type: string
  - description: Name of the configmap containing the 3scale_toolbox remotes list
    name: configName
    type: string
  - description: The system_name of the service
    name: serviceSystemName
    type: string
  - description: The system_name of the plan to create
    name: systemName
    type: string
  - description: The name of the plan to create
    name: name
    type: string
  resources:
    inputs:
    - name: api-artefacts
      type: git
  steps:
  - args:
    - application-plan
    - apply
    - ${inputs.params.destination}
    - ${inputs.params.serviceSystemName}
    - ${inputs.params.systemName}
    - --name=${inputs.params.name}
    command:
    - 3scale
    env:
    - name: HOME
      value: /config
    image: nmasse/3scale-toolbox:master
    name: apply-application-plan
    resources: {}
    volumeMounts:
    - mountPath: /config
      name: toolbox
    - mountPath: /workspace/api-artefacts
      name: swagger
  volumes:
  - name: toolbox
    config:
      configName: toolbox
  - name: swagger
    config:
      configName: swagger
