apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1alpha1","kind":"Task","metadata":{"annotations":{},"name":"import-openapi","namespace":"user1"},"spec":{"inputs":{"params":[{"default":"/workspace/api-artefacts/openapi-spec.yaml","description":"The path to the dockerfile to build","name":"pathToOpenAPI"},{"description":"The name of the 3scale_toolbox remote","name":"destination"},{"default":"http://echo-api.3scale.net","description":"The URL of the API Backend","name":"privateBaseURL"},{"default":"api","description":"The system_name of the service to create","name":"systemName"},{"description":"Name of the config containing the 3scale_toolbox remotes list","name":"configName"}],"resources":[{"name":"api-artefacts","type":"git"}]},"steps":[{"args":["import","openapi","-d","${inputs.params.destination}","${inputs.params.pathToOpenAPI}","--override-private-base-url=${inputs.params.privateBaseURL}","--target_system_name=${inputs.params.systemName}"],"command":["3scale"],"env":[{"name":"HOME","value":"/config"}],"image":"nmasse/3scale-toolbox:master","name":"import-openapi","volumeMounts":[{"mountPath":"/config","name":"toolbox-config"}]}],"volumes":[{"name":"toolbox-config","config":{"configName":"${inputs.params.configName}"}}]}}
  name: import-openapi
  namespace: user1
spec:
  params:
  - default: /workspace/api-artefacts/swagger.yaml
    description: The path to the dockerfile to build
    name: pathToOpenAPI
    type: string
  - description: The name of the 3scale_toolbox remote
    name: destination
    type: string
  - default: http://echo-api.3scale.net
    description: The URL of the API Backend
    name: privateBaseURL
    type: string
  - default: api
    description: The system_name of the service to create
    name: systemName
    type: string
  - description: Name of the config containing the 3scale_toolbox remotes list
    name: configName
    type: string
  resources:
    inputs:
    - name: api-artefacts
      type: git
  steps:
  - args:
    - import
    - openapi
    - -d
    - ${inputs.params.destination}
    - ${inputs.params.pathToOpenAPI}
    - --override-private-base-url=${inputs.params.privateBaseURL}
    - --target_system_name=${inputs.params.systemName}
    command:
    - 3scale
    env:
    - name: HOME
      value: /config
    image: nmasse/3scale-toolbox:master
    name: import-openapi
    resources: {}
    volumeMounts:
    - mountPath: /config
      name: toolbox
    - mountPath: /workspace/api-artefacts
      name: swagger
  volumes:
  - name: toolbox
    config:
      configName: toolbox
  - name: swagger
    config:
      configName: swagger
